config/routes.rb
Rails.application.routes.draw do
  resources :fposts
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fpost.rb
class Fpost < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fposts_controller.rb
class FpostsController < ApplicationController
  before_action :set_fpost, only: %i[ show edit update destroy ]

  # GET /fposts or /fposts.json
  def index
    @fposts = Fpost.all
  end

  # GET /fposts/1 or /fposts/1.json
  def show
  end

  # GET /fposts/new
  def new
    @fpost = Fpost.new
  end

  # GET /fposts/1/edit
  def edit
  end

  # POST /fposts or /fposts.json
  def create
    @fpost = Fpost.new(fpost_params)

    respond_to do |format|
      if @fpost.save
        format.html { redirect_to fpost_url(@fpost), notice: "Fpost was successfully created." }
        format.json { render :show, status: :created, location: @fpost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fposts/1 or /fposts/1.json
  def update
    respond_to do |format|
      if @fpost.update(fpost_params)
        format.html { redirect_to fpost_url(@fpost), notice: "Fpost was successfully updated." }
        format.json { render :show, status: :ok, location: @fpost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fposts/1 or /fposts/1.json
  def destroy
    @fpost.destroy!

    respond_to do |format|
      format.html { redirect_to fposts_url, notice: "Fpost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fpost
      @fpost = Fpost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fpost_params
      params.require(:fpost).permit(:post_title, :post_text, :post_datetime, :post_user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fposts_helper.rb
module FpostsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/fposts/_form.html.erb
<%= form_with(model: fpost) do |form| %>
  <% if fpost.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fpost.errors.count, "error") %> prohibited this fpost from being saved:</h2>

      <ul>
        <% fpost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= react_component("MyForm", {fpost: @fpost}) %>
<% end %>

app/views/fposts/_fpost.html.erb
<div id="<%= dom_id fpost %>">
  <p>
    <strong>Post title:</strong>
    <%= fpost.post_title %>
  </p>

  <p>
    <strong>Post text:</strong>
    <%= fpost.post_text %>
  </p>

  <p>
    <strong>Post datetime:</strong>
    <%= fpost.post_datetime %>
  </p>

  <p>
    <strong>Post user:</strong>
    <%= fpost.post_user_id %>
  </p>

</div>

app/views/fposts/edit.html.erb
<h1>Editing fpost</h1>

<%= render "form", fpost: @fpost %>

<br>

<div>
  <%= link_to "Show this fpost", @fpost %> |
  <%= link_to "Back to fposts", fposts_path %>
</div>

app/views/fposts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Fposts</h1>

<div id="fposts">
  <% @fposts.each do |fpost| %>
    <%= render fpost %>
    <p>
      <%= link_to "Show this fpost", fpost %>
    </p>
  <% end %>
</div>

<%= link_to "New fpost", new_fpost_path %>

app/views/fposts/new.html.erb
<%= react_component("NewPost") %>

<%= render "form", fpost: @fpost %>

app/views/fposts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fpost %>

<div>
  <%= link_to "Edit this fpost", edit_fpost_path(@fpost) %> |
  <%= link_to "Back to fposts", fposts_path %>

  <%= button_to "Destroy this fpost", @fpost, method: :delete %>
</div>

app/views/home/index.html.erb
<%= react_component("Welcome") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webforum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= react_component("Navbar") %>
    <%= yield %>
  </body>
</html>